package constants

const (
	WINDOW_TITLE  = "Space Traders The PixelGames"
	WINDOW_HEIGHT = 600
	WINDOW_WIDTH  = 800

	PANEL_HEIGHT = 100

	PANEL_GAME_CENTER_X = WINDOW_WIDTH / 2
	PANEL_GAME_CENTER_Y = (WINDOW_HEIGHT / 2) - PANEL_HEIGHT

	FONT_PATH       = "./assets/test.ttf"
	FONT_PANEL_SIZE = 12

	MOVE_PLAYER_SIZE = 10
)
