/*
SpaceTraders API

SpaceTraders is an open-universe game and learning platform that offers a set of HTTP endpoints to control a fleet of ships and explore a multiplayer universe.  The API is documented using [OpenAPI](https://github.com/SpaceTradersAPI/api-docs). You can send your first request right here in your browser to check the status of the game server.  ```json http {   \"method\": \"GET\",   \"url\": \"https://api.spacetraders.io/v2\", } ```  Unlike a traditional game, SpaceTraders does not have a first-party client or app to play the game. Instead, you can use the API to build your own client, write a script to automate your ships, or try an app built by the community.  We have a [Discord channel](https://discord.com/invite/jh6zurdWk5) where you can share your projects, ask questions, and get help from other players.   

API version: 2.3.0
Contact: joel@spacetraders.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the GetSupplyChain200ResponseDataExportToImportMap type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetSupplyChain200ResponseDataExportToImportMap{}

// GetSupplyChain200ResponseDataExportToImportMap struct for GetSupplyChain200ResponseDataExportToImportMap
type GetSupplyChain200ResponseDataExportToImportMap struct {
	String []string `json:"string,omitempty"`
}

// NewGetSupplyChain200ResponseDataExportToImportMap instantiates a new GetSupplyChain200ResponseDataExportToImportMap object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetSupplyChain200ResponseDataExportToImportMap() *GetSupplyChain200ResponseDataExportToImportMap {
	this := GetSupplyChain200ResponseDataExportToImportMap{}
	return &this
}

// NewGetSupplyChain200ResponseDataExportToImportMapWithDefaults instantiates a new GetSupplyChain200ResponseDataExportToImportMap object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetSupplyChain200ResponseDataExportToImportMapWithDefaults() *GetSupplyChain200ResponseDataExportToImportMap {
	this := GetSupplyChain200ResponseDataExportToImportMap{}
	return &this
}

// GetString returns the String field value if set, zero value otherwise.
func (o *GetSupplyChain200ResponseDataExportToImportMap) GetString() []string {
	if o == nil || IsNil(o.String) {
		var ret []string
		return ret
	}
	return o.String
}

// GetStringOk returns a tuple with the String field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetSupplyChain200ResponseDataExportToImportMap) GetStringOk() ([]string, bool) {
	if o == nil || IsNil(o.String) {
		return nil, false
	}
	return o.String, true
}

// HasString returns a boolean if a field has been set.
func (o *GetSupplyChain200ResponseDataExportToImportMap) HasString() bool {
	if o != nil && !IsNil(o.String) {
		return true
	}

	return false
}

// SetString gets a reference to the given []string and assigns it to the String field.
func (o *GetSupplyChain200ResponseDataExportToImportMap) SetString(v []string) {
	o.String = v
}

func (o GetSupplyChain200ResponseDataExportToImportMap) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetSupplyChain200ResponseDataExportToImportMap) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.String) {
		toSerialize["string"] = o.String
	}
	return toSerialize, nil
}

type NullableGetSupplyChain200ResponseDataExportToImportMap struct {
	value *GetSupplyChain200ResponseDataExportToImportMap
	isSet bool
}

func (v NullableGetSupplyChain200ResponseDataExportToImportMap) Get() *GetSupplyChain200ResponseDataExportToImportMap {
	return v.value
}

func (v *NullableGetSupplyChain200ResponseDataExportToImportMap) Set(val *GetSupplyChain200ResponseDataExportToImportMap) {
	v.value = val
	v.isSet = true
}

func (v NullableGetSupplyChain200ResponseDataExportToImportMap) IsSet() bool {
	return v.isSet
}

func (v *NullableGetSupplyChain200ResponseDataExportToImportMap) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetSupplyChain200ResponseDataExportToImportMap(val *GetSupplyChain200ResponseDataExportToImportMap) *NullableGetSupplyChain200ResponseDataExportToImportMap {
	return &NullableGetSupplyChain200ResponseDataExportToImportMap{value: val, isSet: true}
}

func (v NullableGetSupplyChain200ResponseDataExportToImportMap) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetSupplyChain200ResponseDataExportToImportMap) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


